-- ----------------------------------------------------------------------------
-- Put here INSERT statements for inserting data required by the application
-- in the "pa-project" database.
-------------------------------------------------------------------------------

INSERT INTO Lesion (lesionName, description, medication, lesionType) VALUES ('Contusion','They are produced by a blow to the muscle and can cause inflammation, pain and bruising.', 'Local cold and repose.', 1);
INSERT INTO Lesion (lesionName, description, medication, lesionType) VALUES ('Cramp','In this case, the sudden contraction of the muscle is maintained over time, causing pain and limiting movement.', 'Analgesic, stretching and massage.', 1);
INSERT INTO Lesion (lesionName, description, medication, lesionType) VALUES ('Distension','It is also called hyperextension or muscle elongation. It is generated when the muscle is stretched more than it can cover. It causes a diffuse pain that lasts over time.', 'Analgesic, repose and ice in the area.', 1);
INSERT INTO Lesion (lesionName, description, medication, lesionType) VALUES ('Fibrillar or Muscle tear','One or more fibers of muscle tissue are broken and its severity depends on the extent of the injury and its duration. The pain is sharp and very localized, although the most severe ones cause immediate immobility of the muscle.', 'Cold application in the first phase, massage, red clay and minimum rest 15 days ', 1);
INSERT INTO Lesion (lesionName, description, medication, lesionType) VALUES ('Complete muscle tear','The muscle breaks completely. The pain is intense and the inability to move the muscle is felt, causing immobility.', 'Rest is the best way to recover from a muscle tear. In addition, when suffering the tear, the patient must apply cold to the affected area (ice or a cold compress, for 10 or 15 minutes). You can then place a compression bandage around the muscle for 20 minutes. After this time, you must remove it for five minutes and then replace it. After the third or fourth day, thermotherapy can also be applied to increase the metabolism of the affected muscle.', 1);

INSERT INTO Lesion (lesionName, description, medication, lesionType) VALUES ('Enthesitis','It is characterized by inflammation of the tendon attachments to the bone due to fibrillar micro-tears caused by overload. In a high percentage of cases it is a recurrent injury.', 'Rest of the injured region and use of medications with anti-inflammatory properties, such as aspirin and ibuprofen, to relieve pain. Mild stretching exercises can also be performed, under the guidance of the physiotherapist or traumatologist, with the aim of reducing the pressure in the area a little.', 2);
INSERT INTO Lesion (lesionName, description, medication, lesionType) VALUES ('Tendinitis','In this case, the body of the tendon is generally inflamed, although it can also affect the sheath (tenosynovitis) or the peritendon (peritendinitis).', 'To relieve pain and reduce inflammation. It is usually medicated with drugs such as painkillers, corticosteroids, or platelet-rich plasma. In addition to physical therapy to stretch and strengthen the affected muscle and tendon', 2);
INSERT INTO Lesion (lesionName, description, medication, lesionType) VALUES ('Partial break','It usually occurs especially in the longer tendons and is characterized by the breakage of a few fibers.', 'Keep the tendon at rest using crutches. Ice the area. Take over-the-counter pain relievers. Keeping the ankle at rest for the first few weeks, usually in a walking boot with wedge heels or a cast, or with the foot flexed downward.', 2);
INSERT INTO Lesion (lesionName, description, medication, lesionType) VALUES ('Total break','The tendon is completely ruptured and usually occurs in older athletes.', 'Keep the tendon at rest using crutches. Ice the area. Take over-the-counter pain relievers. Keeping the ankle at rest for the first few weeks, usually in a walking boot with wedge heels or a cast, or with the foot flexed downward.', 2);
INSERT INTO Lesion (lesionName, description, medication, lesionType) VALUES ('Dislocation','The tendon is displaced from its natural position when performing certain movements. It is a very rare injury.', 'Rest the dislocated joint. Do not repeat the action that caused your injury and try to avoid painful movements.Apply ice and heat. Take an analgesic. Maintain the joint''s range of motion.', 2);

INSERT INTO Lesion (lesionName, description, medication, lesionType) VALUES ('Bone','Bone joint injuries can be fractures, with partial or total breakage of the bone, and dislocations, which cause one of the bones that make up the joint to come out of its normal position.', 'Treatment of any serious complication. Pain relief. Protection, Rest, Ice, Compression and Elevation. Realignment (reduction) of fragments that are out of place. Immobilization, usually with a splint or cast. On certain occasions, surgical intervention', 3);
INSERT INTO Lesion (lesionName, description, medication, lesionType) VALUES ('Cartilage','They cover the end of the bone and make the joint work properly, preventing friction between the bones (the menisci are cartilage). Among the most frequent injuries caused by sport, we must highlight chondromolacia, which implies the alteration of the cartilage generally as a consequence of trauma, and osteochondritis, which is the inflammation of the cartilage.', 'Treatment for chondromalacia patellae can be done with physical therapy, with the aim of improving the position of the patella and the function of the knee, in addition to the use of anti-inflammatory and analgesic medications to control inflammation and pain, which should be prescribed by the doctor and used as directed.', 3);
INSERT INTO Lesion (lesionName, description, medication, lesionType) VALUES ('Synovial membrane','It is a membrane that covers the entire joint to protect it and is filled with synovial fluid. The most common injury is synovitis, that is, an irritation of the inflammation of the membrane due to a blow, a twist of the joint or poor posture, which causes an increase in the volume of synovial fluid.', 'Usually it will begin with the application of cold and heat, rest and the taking of anti-inflammatories or even injected corticosteroids. It generally includes taking anti-inflammatories, in some cases corticosteroid injections, the application of heat and cold, and rest. Electrostimulation can also be a good complement, especially if combined with the application of ice to the knee, since it facilitates the relaxation of the muscles and helps to reduce both pain and inflammation.', 3);
INSERT INTO Lesion (lesionName, description, medication, lesionType) VALUES ('Stock exchanges','They are soft sac-like structures found between the muscles, tendons, ligaments and bony prominences that make up the joint and whose function is to avoid friction of the bones during movement and cushion the pressure exerted on the joint . The most common injury is bursitis, that is, an inflammation of the bursa, which can become chronic after successive episodes. It can be caused by bruising, repetitive motion, and continued pressure on it.', 'Applying ice to the affected joint three or four times a day for the first few days. Joint compression. Do not lie down putting weight on the affected joint. Taking anti-inflammatories. Avoid overexertion and, if possible, the use of the joint.', 3);

INSERT INTO Lesion (lesionName, description, medication, lesionType) VALUES ('Hyperkyphosis','It is an increase in the curvature of the dorsal area.', 'Medicines. Treatment of osteoporosis associated with hyperkyphosis with antiresorptive or bone-building drugs is common. Surgery. Functional braces and bandages: Corsets and other spinal orthoses have been used to try to reduce the kyphotic curve. Exercise.', 4);
INSERT INTO Lesion (lesionName, description, medication, lesionType) VALUES ('Hyperlordosis','In this case, the curvature of the lumbar area of ​​the spine increases.', 'Physiotherapy sessions and with the practice of physical exercises such as swimming or Pilates. In physiotherapy, various exercises should be performed that strengthen the muscles that are weakened, specifically those of the abdomen, as well as stretching of the muscles that are atrophied, stretching the spine.', 4);



INSERT INTO Stretching (stretchingName, description, stretchingType) VALUES ('Hamstring Stretch',' 1) Sit on the floor with one leg straight and the other bent with the foot as close to the pubis as possible. 2) Flex the trunk trying to touch the foot with both hands', 1);
INSERT INTO Stretching (stretchingName, description, stretchingType) VALUES ('Buttocks Stretch',' 1) Lie on your back with your legs straight. 2) Bend one leg and holding with your hands, try to bring your foot to the opposite shoulder. 3) Hold the stretch for 15 seconds and relax', 2);
INSERT INTO Stretching (stretchingName, description, stretchingType) VALUES ('Calf Stretch',' 1) Stand facing a wall with your arms supported. 2) One leg bent and the other stretched back. 3) Bring your pelvis forward, keeping your back straight and without taking your heel off the ground. 4) Hold the position for about 20 seconds.', 3);
INSERT INTO Stretching (stretchingName, description, stretchingType) VALUES ('Adductors Stretch',' 1) Sit on the floor. 2) Join the soles of your feet and hold them together with your hands. 3) Rest your elbows on the inside of your legs. 4) Lean your upper body forward from your hips.', 4);
INSERT INTO Stretching (stretchingName, description, stretchingType) VALUES ('Shoulder Stretch',' 1) Stand up straight. 2) Bend one arm and place it over the opposite shoulder 3) Push the elbow back with the help of the other hand.', 5);
INSERT INTO Stretching (stretchingName, description, stretchingType) VALUES ('Quadriceps Stretch',' 1) Lie on your side 2) Grab one foot with the hand on the same side. 3) Bend your knee bringing your foot to the glute', 6);
INSERT INTO Stretching (stretchingName, description, stretchingType) VALUES ('Back Stretch',' 1) Stand up straight 2) Raise your arms above your head with your fingers interlocked and your palms facing up. 3) Push your hands up and slightly back', 7);

INSERT INTO Stretching (stretchingName, description, stretchingType) VALUES ('Pectoral Stretch',' 1) Interlock your fingers behind your back with your palms facing within. Slightly raise your arms straight from behind, while keeping your back straight', 8);
INSERT INTO Stretching (stretchingName, description, stretchingType) VALUES ('Crotch Stretch',' 1) Stretches the front of the thigh and groin, helping to keep the pelvis in the correct position and minimizing the risk of pain in the lower back. 2) Hold for 30 seconds and then switch legs.', 9);
INSERT INTO Stretching (stretchingName, description, stretchingType) VALUES ('Triceps Stretch',' 1) Catch an elbow above the head and pull gently from behind of the head, without tensing the neck, keeping the back straigh', 10);



INSERT INTO Exercise (exerciseName, description, objective, exerciseType) VALUES ('Defense of cuts','1x1 from midfield with 2 passers on the wing. Player with ball starts by dribbling to either side to hit one of the passers and cut into a corner. Defender will defend the cut When the ball reaches the second passer the attacker cuts into the zone, if he receives within 3 seconds he plays a 1x1.', 'Improve defense and 1x1 ', 1);
INSERT INTO Exercise (exerciseName, description, objective, exerciseType) VALUES ('Defense 2x2','Four players and one ball Stand in the midfield corners Start at a baseline Defenders need to sprint to get there on time A 2x2 situation will subsequently be created.', 'Improve attack and defense 2x2', 1);
INSERT INTO Exercise (exerciseName, description, objective, exerciseType) VALUES ('Shot with direct block and continuation','Two rows of players. In the row located at 6.25 they will have all but the first ball and in the baseline group all with the ball. The player in the back will send a pass. When he receives he waits for the direct block. The player who blocks remains open and receives the ball from the next in line. The player who has received the block goes out to take a shot. The players catch their rebound and change rows.', ' Improve shot with direct block', 1);
INSERT INTO Exercise (exerciseName, description, objective, exerciseType) VALUES ('Possession','The squad is divided into 2 teams. 1 more "goal" is randomly placed than there are players in each team. The fundamental objective is to maintain possession and get as many as possible. Both will be achieved when a pass is made. from any of the "goals" or penetrates through them. If the defending team recovers the ball, it goes on to attack.', 'Improve possession and communication', 1);
INSERT INTO Exercise (exerciseName, description, objective, exerciseType) VALUES ('Shot after block at the low post','A group of 8 or 9 players; a player (pitcher) under the ring, 2 at his sides (blockers) outside the zone, the rest with the ball in 2 rows at 6.25 The pitcher goes to one side takes advantage of the teammate''s block to receive a Pass from one of the rows and finish with a shot to the basket The blocker cuts the area horizontally and takes advantage of the block of the third player to finish with a shot and so on.', 'Improve outside shooting and inside blocks', 1);

INSERT INTO Exercise (exerciseName, description, objective, exerciseType) VALUES ('Shot by threesomes','Three players with 2 balls A static passer who will send strong, high and well directed passes A rebounder who must catch the rebounds and pass them quickly and with good passes A shooter comes out to meet the forward with a good change of pace, gives A deep dribble to the low post and jump shot. After landing balanced, start to the wing and repeat.', 'Improve shot and shooting technique', 2);
INSERT INTO Exercise (exerciseName, description, objective, exerciseType) VALUES ('Triangle','The players positioned in a triangular shape pass the ball. The controls will be oriented. The passes can be made with one or two hands.', 'Improve passes and communication', 2);
INSERT INTO Exercise (exerciseName, description, objective, exerciseType) VALUES ('Pass, catch, feint and shoot.','Pass between two players and after a feint shoot to the basket, it will start with a long throw by the defender.', 'Improve Pass, catch, feint and shoot', 2);
INSERT INTO Exercise (exerciseName, description, objective, exerciseType) VALUES ('High post and low post','Three players with 2 balls. A rebounder who must catch the rebounds and pass them quickly. The shooter starts cutting to receive at the low post, after shooting goes up to receive at the high post and repeats. A passer at the wing, who can work differently. types of pass to the low post.', 'Improve shooting and play at the high post and at the low post. Also improve passes', 2);
INSERT INTO Exercise (exerciseName, description, objective, exerciseType) VALUES ('Penetration wheel and trays','Divide the squad into 2 rows on each side of the zone The players in the row with the ball make lateral penetrations to the basket ending with a layup The players in the opposite row pick up the rebound The rows are exchanged Perform the exercise on both sides of the field to improve the handling of both hands.', 'Improve trays and penetrations', 2);

INSERT INTO Exercise (exerciseName, description, objective, exerciseType) VALUES ('Get out of the circle','Try to get out through the gaps left by the teammates between the legs, arms or above. Stand hand in hand and inside a player.', 'Improve physique and speed', 3);
INSERT INTO Exercise (exerciseName, description, objective, exerciseType) VALUES ('Team hunting','2 teams play to be eliminated. Players will have the ball in their hands and may not take more than 3 steps with it. One player will be eliminated when touched with the ball. The player who leaves the delimited field will also be eliminated.', 'Improve physique, speed and communication', 3);
INSERT INTO Exercise (exerciseName, description, objective, exerciseType) VALUES ('Farlek to the whole field','The team is divided into 4 groups that stand on the baseline. The first group runs at speed (80%) the distance of 6.25 to 6.25 m and then walking (recovery). relays (one arrives, the other leaves). 6 trips are made with 4 groups Subsequently, they are reduced to 3 groups and with the same dynamics, 4 trips are made. Finally, 2 groups are made and 2 trips are made.', 'Improve physique, speed and communication', 3);
INSERT INTO Exercise (exerciseName, description, objective, exerciseType) VALUES ('Little handkerchief with balloon','Handkerchief game but with the ball. When the coach calls out a number, one player from each team will come out. It consists of catching the ball and driving it without the other player taking the ball from him.', 'Improve physique, speed and communication', 3);
INSERT INTO Exercise (exerciseName, description, objective, exerciseType) VALUES ('Remove the bib','All but one player will have a bib "hooked" on the back of the pants. The one who does not have the bib will try to take it off one of his teammates. The game will end when no player has a bib.', 'Improve physique, speed and communication', 3);

INSERT INTO Exercise (exerciseName, description, objective, exerciseType) VALUES ('Counterattack 2 vs 2','It is distributed to the players in pairs. It is about making counterattacks in a real situation 2 against 2. If the attacking team gets a basket, they pass the ball to the waiting team and change their position with it. If he does not get a basket, he stays to defend and the team that defended him goes to the waiting position (to attack). Go adding the points that each team gets.', 'Improve ball handling, speed, counterattack and communication', 4);
INSERT INTO Exercise (exerciseName, description, objective, exerciseType) VALUES ('2 against 2 with external supports','Two attackers against 2 defenders with 2 outside supports located outside the 6.25 line. If the attackers get a basket, the defenders continue in their role and they change their role with the outside players. If they do not get a basket, they stay to defend against the player. outside equipment.', 'Improve 2x2 Attacks', 4);
INSERT INTO Exercise (exerciseName, description, objective, exerciseType) VALUES ('Counterattack of 11','Three players in the center of the field will start attacking. Two players will be positioned in each zone as defenders and another 2 in each half of the field. They attack 3 for 2 and all go to the rebound. The one who catches the rebound quickly passes to one of those who They wait on the wings. The one who caught the rebound and the 2 players who were waiting organize to attack the other ring. The 4 that remain split up: 2 defend and 2 wait on the wings.', 'Improve ball handling, speed, counterattack and communication', 4);
INSERT INTO Exercise (exerciseName, description, objective, exerciseType) VALUES ('Global Score 1x1','Situations are played 1 against 1 in midfield with the goal of reaching a certain number of points (7). All the outstanding offensive and defensive aspects are scored; Basket; 1, 2 or 3 points. Rebound; 1 pt. Stole; 1 pt. Plug; 1 pt. Robbery and driving to the center of the field; 1 point .. It is about finishing with the exact points to win.', 'Improve 1x1', 4);
INSERT INTO Exercise (exerciseName, description, objective, exerciseType) VALUES ('1 against 2 and counter attack 2 against 1','Distribute the squad in groups of 3. One player starts the counterattack with the ball from the back of the court towards the opponent''s basket. After 2 seconds the other two players go in search of him and try to prevent him from hitting the basket. basket or after recovering the ball, a 2x1 counterattack is started in the opposite direction and exchanging functions.', 'Improve counterattacks with advantage', 4);

INSERT INTO Exercise (exerciseName, description, objective, exerciseType) VALUES ('Eaves specific: Exterior finishes','The front of the zone is divided into 3 different areas. In each of them the forward will receive a pass from each of the passers (different positions). The objective will be to finish the maximum number of possible actions in the basket. The passes come from different heights and directions so movement and body orientation will be necessary to finish quickly and efficiently.', 'Improve exterior finishes', 5);
INSERT INTO Exercise (exerciseName, description, objective, exerciseType) VALUES ('Eaves specific: completion with opposition','The front of the zone is divided into 3 areas. In each one of them a forward will be placed. The objective is to look for quick shots from different positions and with opposition. Two passers from different outside positions will be in charge of feeding balls to the attackers who They will not be able to leave their launching zones. A defender can move freely to abort the offensive action. Attackers have the possibility to combine with each other in the presence of opposition.', 'Improve shot with opposition', 5);

INSERT INTO Exercise (exerciseName, description, objective, exerciseType) VALUES ('Group coordination','The whole team moves around the coach .. The coach orders different movements matched with numbers that he is shouting .. Some of these gestures and movements have to be done by the whole group at the same time .. Collective coordination will be rewarded and uncoordination will be punished ..Gestures: Chut in the air, applause jumping, go towards the center, ....', 'Group coordination', 6);
INSERT INTO Exercise (exerciseName, description, objective, exerciseType) VALUES ('Land, sea and air','It takes place in the locker room. The whole team sitting in a circle. The coach throws the ball into the hands of the players shouting: Land, sea or air. They quickly return the ball to him shouting the name of an animal corresponding to that habitat.', 'Improve team relationship', 6);
INSERT INTO Exercise (exerciseName, description, objective, exerciseType) VALUES ('Concentration and reaction','The players move freely around the field and must react quickly to the coach''s instructions. The game consists of carrying out the coach''s orders as quickly as possible.', 'Concentration and reaction', 6);
INSERT INTO Exercise (exerciseName, description, objective, exerciseType) VALUES ('Running with eyes closed towards the group','At a distance of 10 meters approx. A player stands in front of the group, he has to close his eyes and run with speed towards the teammates. The group has to try to stop him by grabbing him carefully when he reaches their area.', 'Improve group confidence', 6);
INSERT INTO Exercise (exerciseName, description, objective, exerciseType) VALUES ('Numbers without "stepping on"','The team in a group and static The game consists of saying the next number without at any time 2 partners agreeing. The coach will start with 1. As many numbers as there are players must be said. the numbering but the interventions must be random and spontaneous. The objective is to complete the sequence or entire round in the shortest possible time.', 'Group coordination and team relationship', 6);

INSERT INTO Exercise (exerciseName, description, objective, exerciseType) VALUES ('Counterattack wheel between 4 players','4 combinations in a row between 4 players alternating positions: the one who serves (4) takes the place of the one who bounces and passes (1), this one the one who runs and enters the basket (3), and this in turn the one who runs bounces.', 'Improve Counterattack between 4 players', 7);
INSERT INTO Exercise (exerciseName, description, objective, exerciseType) VALUES ('Band: Vertical and blind locks','Side kick in which the base part of the low post to go to receive the outside The base moves to the opposite side to make a pick and roll with the high post (4) The (3) makes a blind block to the defender of (5) and cuts the area towards the high post. (4) after making the pick and roll performs a vertical block to the defender of (3). Two possible finishes are sought: a) Pass and outside finish by ( 3). b) Inside pass and 1x1 finish of (5).', 'Improve Vertical and blind locks', 7);
INSERT INTO Exercise (exerciseName, description, objective, exerciseType) VALUES ('Band: Outside shot in last seconds','The 4 attackers are in a box position; 2 high posts and 2 low posts. The high post (2) cuts on the serving side taking advantage of the blocking of the other high post (5). The low post on the opposite side to the serve (3) goes to the outside cutting the area and receiving consecutively the blocks of (5) and (4). After receiving the ball from the server, this player (3) finishes with an outside shot.', 'Improve Outside shot in last seconds', 7);
INSERT INTO Exercise (exerciseName, description, objective, exerciseType) VALUES ('Background: Orlando Magic','With starting position in box; (1) base and (4) in low post, (5) and (2) in high post The base (1) blocks the defender from (5) cutting diagonally, after which he receives the block from (4) to go outside and receive the ball After the serve the wing (3) moves to the opposite side to receive a block from the high post (2) .The action is finished with a pick and roll from (4) to (1) and two possibilities; a) Completion of (1) in shooting. b) Go to (3) and finish it.', 'Improve background play', 7);
INSERT INTO Exercise (exerciseName, description, objective, exerciseType) VALUES ('Background: Box horizontal - vertical','Starting at box; (1) and (3) in low post, (4) and (5) in high post. Action begins with vertical block from (4) to (1). Then (4) cuts the zone horizontally and receives a block of (3) while (1) blocks the high post (5) that cuts in the direction of the basket. The service is made on (4) who combines with the point guard (1) waiting for (2) to reach the outside after blocking (5) for outside throw.', 'Improve Background: Box horizontal - vertical', 7);

INSERT INTO Exercise (exerciseName, description, objective, exerciseType) VALUES ('Runs with the ball','For example, while doing a soft trot, the players are bouncing a ball along the court. Making changes of pace, direction, or tickets to the basket.', 'Warm-up', 8);
INSERT INTO Exercise (exerciseName, description, objective, exerciseType) VALUES ('Passes','This exercise would be carried out in groups, one player facing another who can make passes in a linear fashion or by tapping the ball once against the ground. There are also variations where some groups are formed and one from one group and the next from the other are placed interspersed, where a couple of balls intervene and they must concentrate on receiving one of them from the team to which they belong. This exercise stimulates concentration.', 'Improve Passes', 8);
INSERT INTO Exercise (exerciseName, description, objective, exerciseType) VALUES ('Shooting','Here in the warm-up, the players in a row would launch from certain positions, such as free throws or running shots.', 'Warm-up shooting', 8);
INSERT INTO Exercise (exerciseName, description, objective, exerciseType) VALUES ('Rehearsed plays','Any specific match situation that you want to improve or rehearse. Each of the players would be placed in a strategic position, simulating some future situation in the game, in this way they practice plays that they have rehearsed throughout their training, in this way they are not only able to exercise their body, but also their mind.', 'Remember plays and relaxing', 8);
